apiVersion : apps/v1
kind: Deployment
metadata:
  name: "apdemoquick-a931"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "apdemoquick-a931"
  template:
    metadata:
      labels:
        app: "apdemoquick-a931"
    spec:
      containers:
        - name: "apdemoquick-a931"
          image: "demoliveaksws.azurecr.io/apdemoquick"
          ports:
          - containerPort: 3000