on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n demoliveaksws -g demoliveaksws88d8-rg --location "West Europe" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n demoliveaksws --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n demoliveaksws --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n demoliveaksws --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: demoliveaksws.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t demoliveaksws.azurecr.io/apdemoquick:${{ github.sha }}
        docker push demoliveaksws.azurecr.io/apdemoquick:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_apdemoquick_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep apdemoquick9b24 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace apdemoquick9b24`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: apdemoquick9b24
        container-registry-url: demoliveaksws.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: apdemoquickdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: apdemoquick9b24
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          demoliveaksws.azurecr.io/apdemoquick:${{ github.sha }}
        imagepullsecrets: |
          apdemoquickdockerauth